src/Web/Pages/Article.cshtml.cs
using Gwenael.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using Gwenael.Domain;
using System.Linq;
using Amazon.S3;
using Amazon;
using Amazon.S3.Model;
using System.IO;
using Gwenael.Web.FctUtils;

namespace Gwenael.Web.Pages
{
    public class ArticleModel : PageModel
    {
        private readonly GwenaelDbContext _context;
        private IList<NewPage> NewPages { get; set; }


        public ArticleModel(GwenaelDbContext context)
        {
            _context = context;
        }
        public List<Article> Articles { get; set; }
        public Article article { get; set; }
        public List<Article> b;
        public List<Article> a;

        public async Task<IActionResult> OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _context);
                if (Permission.EstAdministrateur(idConnectedUser, _context))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }


            Articles = await _context.Articles.ToListAsync();
            NewPages = await _context.NewPages.ToListAsync();
            ViewData["NewPages"] = NewPages;

            string id = Request.Query["id"];
            int intId = Int32.Parse(id);


            Article b = Articles.Where(article => article.Id == intId).First();
            ViewData["tst"] = "tst";
            ViewData["unArticle"] = b;
            var s3Client = new AmazonS3Client("AKIAVDH3AEDD6PUJMKGG", "kKV5WKu0tFe8Svl2QdTIMIydLc7CGSMiy2h+KOvV", RegionEndpoint.CACentral1);
            var buckets = await s3Client.ListBucketsAsync();



            foreach (var bucket in buckets.Buckets)
            {
                var objects = await s3Client.ListObjectsAsync(bucket.BucketName);

                if (objects != null)
                {
                    var tst = objects.S3Objects;
                    ViewData["unObjet"] = tst;


                    var s3Requ = new Amazon.S3.Model.GetObjectRequest
                    {
                        BucketName = bucket.BucketName,
                        Key = string.Join(",", objects.S3Objects[0].Key)
                    };

                    var s3Resp = s3Client.GetObjectAsync(s3Requ);
                    var res = s3Resp.Result;

                }
            }



            return Page();
        }

    }
}

src/Web/Pages/Tutoriel/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Globalization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using System.Reflection;
using System.Threading.Tasks;
using OfficeOpenXml;
using System.Linq;
using CsvHelper;
using CsvHelper.Configuration;
using Gwenael.Domain;
using Gwenael.Domain.Entities;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Packaging;
using NuGet.Protocol;
using Spk.Common.Helpers.String;
using Gwenael.Web.FctUtils;

namespace Gwenael.Web.Pages
{
    public class TutorielIndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public InputModel Input { get; set; }
        private IList<NewPage> NewPages { get; set; }


        private readonly GwenaelDbContext _db;


        public class InputModel
        {
            public List<Tutos> lstTutoriels { get; set; }
            public bool droitAccess { get; set; }
            public List<CategoriesTutos> lstCategories { get; set; }

        }
        public TutorielIndexModel(GwenaelDbContext pDb) => _db = pDb;

        public Guid ObtenirIdDuUserSelonEmail(string email)
        {
            User user = (User)_db.Users.Where(u => u.UserName == email).First();
            return user.Id;
        }
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            NewPages = _db.NewPages.ToList();
            ViewData["NewPages"] = NewPages;

            Input = new InputModel();
            Input.droitAccess = false;
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                {
                    Input.droitAccess = true;
                }
            }
            Input.lstTutoriels = _db.Tutos.ToList();
            Input.lstCategories = _db.CategoriesTutos.ToList();

            return Page();
        }

        public IActionResult OnPost()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            return Page();
        }

        public IActionResult OnPostRedirectCreationTuto() 
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                return RedirectToPage("CreationTuto");
            }

        public class RechercherFiltre
        {
            public bool radioFiltreEstPublie { get; set; }
            public string radioFiltre { get; set; }
            public string rechercheValeur { get; set; }
            public string cat { get; set; }
        }

        public IActionResult OnPostRecherche([FromForm] RechercherFiltre formData)
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                List<Tutos> t = new List<Tutos>();
                if (!formData.cat.IsNullOrEmpty() && formData.cat != "Toutes")
                {
                    List<CategoriesTutos> cats = _db.CategoriesTutos.Where(c => c.Nom.Contains(formData.cat)).ToList();
                    if (cats.Count > 0)
                    {
                        if (!formData.rechercheValeur.IsNullOrEmpty())
                        {
                            t = _db.Tutos.Where(t => t.EstPublier ==
                            formData.radioFiltreEstPublie && t.Categorie == cats[0]
                            && t.Titre.Contains(formData.rechercheValeur)).ToList();
                        }
                        else
                        {
                            t = _db.Tutos.Where(t => t.EstPublier ==
                            formData.radioFiltreEstPublie && t.Categorie == cats[0]).ToList();
                        }
                    }
                }
                else if (!formData.rechercheValeur.IsNullOrEmpty())
                {
                    List<CategoriesTutos> catTemp = _db.CategoriesTutos.ToList();
                    foreach (var item in catTemp)
                    {
                        t.AddRange(_db.Tutos.Where(t => t.EstPublier == formData.radioFiltreEstPublie
                        && t.Categorie == item && t.Titre.Contains(formData.rechercheValeur)).ToList());
                    }
                }
                else
                {
                    List<CategoriesTutos> catTemp = _db.CategoriesTutos.ToList();
                    foreach (var item in catTemp)
                    {
                        t.AddRange(_db.Tutos.Where(t => t.EstPublier == formData.radioFiltreEstPublie && t.Categorie == item).ToList());
                    }
                }
                return StatusCode(201, new JsonResult(t));
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }

        public IActionResult OnPostObtenirDroit()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                    if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                    {
                        return StatusCode(200, true);
                    }
                }
                return StatusCode(200, false);
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }
    }
}

src/Web/Pages/indexArticles.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using Gwenael.Domain;
using Gwenael.Domain.Entities;
using IdentityServer4.Extensions;
using Gwenael.Web.FctUtils;

namespace Gwenael.Web.Pages
{
    public class ArticleIndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public InputModel Input { get; set; }
        private IList<NewPage> NewPages { get; set; }


        private readonly GwenaelDbContext _db;

        public class InputModel
        {
            public List<Domain.Entities.Article> lstArticles { get; set; }
            public bool droitAccess { get; set; }

        }

        public class RechercherFiltre
        {
            public bool radioFiltreEstPublie { get; set; }
            public string radioFiltre { get; set; }

            public string rechercheValeur { get; set; }
        }

        public ArticleIndexModel(GwenaelDbContext pDb) => _db = pDb;

        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }


            NewPages = _db.NewPages.ToList();
            ViewData["NewPages"] = NewPages;

            Input = new InputModel();
            Input.droitAccess = false;
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                {
                    Input.droitAccess = true;
                }
            }

            Input.lstArticles = _db.Articles.ToList();

            return Page();
        }

        public IActionResult OnPost() => Page();

        public IActionResult OnPostRedirectCreationArticle()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }
            return RedirectToPage("CreationArticle");
        }

        public IActionResult OnPostRecherche([FromForm] RechercherFiltre formData)
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }
                List<Article> lstArticles = new List<Article>();
                //if (!formData.cat.IsNullOrEmpty() && formData.cat != "Toutes")
                //{
                //    List<CategoriesTutos> cats = _db.CategoriesTutos.Where(c => c.Nom.Contains(formData.cat)).ToList();
                //    if (cats.Count > 0)
                //    {
                //        if (!formData.rechercheValeur.IsNullOrEmpty())
                //        {
                //            t = _db.Tutos.Where(t => t.EstPublier ==
                //            formData.radioFiltreEstPublie && t.Categorie == cats[0]
                //            && t.Titre.Contains(formData.rechercheValeur)).ToList();
                //        }
                //        else
                //        {
                //            t = _db.Tutos.Where(t => t.EstPublier ==
                //            formData.radioFiltreEstPublie && t.Categorie == cats[0]).ToList();
                //        }
                //    }
                //}
                if (!formData.rechercheValeur.IsNullOrEmpty())
                {
                    lstArticles.AddRange(_db.Articles.Where(article => article.EstPublier == formData.radioFiltreEstPublie
                     && article.Titre.Contains(formData.rechercheValeur)).ToList());
                }
                //if (!formData.rechercheValeur.IsNullOrEmpty())
                //{
                //    lstArticles.AddRange(_db.Articles.Where(article => article.Titre.Contains(formData.rechercheValeur)).ToList());
                //}
                else
                {
                    lstArticles.AddRange(_db.Articles.Where(article => article.EstPublier == formData.radioFiltreEstPublie ).ToList());             
                }
                return StatusCode(201, new JsonResult(lstArticles));
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }


        public Guid ObtenirIdDuUserSelonEmail(string email)
        {
            User user = (User)_db.Users.Where(u => u.UserName == email).First();
            return user.Id;
        }

        public IActionResult OnPostObtenirDroit()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                    if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                    {
                        return StatusCode(200, true);
                    }
                }
                return StatusCode(200, false);
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }

    }


}

src/Web/Pages/Article.cshtml
@page
@using Web.Pages
@using Domain.Entities
@model Web.Pages.ArticleModel
@{ ViewData["Title"] = "Home page"; }


<div id="container" class="container">


    @{ Article unArticle = ViewData["unArticle"] as Article;
        string articleC = unArticle.InerText;
        var imageRef = ViewData["uneImage"];

        <h2 style="margin-bottom: 2rem; text-align: center">@unArticle.Titre</h2>



        @if (@unArticle.LienImg != null)
        {
            <img style="margin-bottom: 2rem; width: 100%" src="https://mediafileobjectifresiliance.s3.ca-central-1.amazonaws.com/@unArticle.LienImg"  class="divBanner" >
        }

        <div>
            <script>
            var article = '@articleC';
            tst = document.getElementById('container')


            function htmlDecode(input) {
                var e = document.createElement('div');
                e.innerHTML = input;
                return e.childNodes[0].nodeValue;
            }

            var tst2 = htmlDecode(article)
            tst.innerHTML += tst2;
            </script>
        </div>
    }

    @if (ViewData["estAdmin"] as string == "true")
    {
        <a href="/CreationArticle?id=@unArticle.Id" class="btn">Modifier</a>
    }


</div>

src/Web/Pages/CreationArticle.cshtml
@page
@model Web.Pages.CreationArticle
@using Domain.Entities


<div class="container">
    <h1 style="text-align:center">Creation d'un article</h1>
    <div style="margin:3rem;">

        <form method="post" enctype="multipart/form-data">
            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text" id="inputTitre">Titre</span>
                <input type="text" id="titre" class="form-control" aria-label="Titre" aria-describedby="Titre" name="titre" asp-for="Input.Titre">
            </div>

            <h3 style="text-align: left">Redaction de l'article :</h3>
            <textarea name="inerText" asp-for="Input.TextArea"></textarea><br /><br />

            <input multiple="multiple" asp-for="Input.FormFile" class="form-control" type="file" id="formFile"><br/>

            @if (ViewData["Modifier"] as string == "true")
            {
                <button id="btnCreeTuto" data-creationTuto type="submit" value="Upload" class="btn btn-primary">Modifier</button>
            }
            else
            {
                <button id="btnCreeTuto" data-creationTuto type="submit" value="Upload" class="btn btn-primary">Créé Article</button>
            }

        </form>


        @if (ViewData["NewArticleCreated"] as String == "true")
        {
            <script>
                    window.onload = function () {
                    window.scriptToastNotification.AjouterNotification("Article valider", true);
                    setTimeout(function () {
                    }, 3600);
                }
            </script>

        }

        @if (ViewData["erreurChamps"] as String == "true")
        {
            <script>
                window.onload = function () {
                    window.scriptToastNotification.AjouterNotification("Les champs de l'article ne sont pas valide", false);
                    setTimeout(function () {
                    }, 3600);
                }
            </script>

        }





    </div>
</div>

<script src="~/javascript/utils/ToastNotification.js" asp-append-version="true"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.0.20/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({ selector: 'textarea' });
</script>

src/Web/Pages/Index.cshtml
@page
@using Web.Pages
@using Domain.Entities
@model Web.Pages.IndexModel
@{
    ViewData["Title"] = "Accueil";
}

<div>
    <img src="../images/Banniere_foret.jpg" class="divBanner" style="width:100%" />
</div>


<div class="container">
    <div class="first-alf-container">
        <div class="pageBox">
            <h3>Notre projet:</h3>
            <p class="divIntro">
                Favoriser l’émergence d’un changement sociétal par l’expérimentation et la mise en place d’initiatives citoyennes.
                La résilience écologique est la capacité d’un système vivant à retrouver les structures et les fonctions de son état
                de référence après une perturbation. La résilience communautaire est la capacité d’une communauté de continuer à vivre,
                fonctionner, se développer et s’épanouir après un traumatisme ou une catastrophe.
            </p>

        </div>
    </div>

    <div class="second-alf-container">
        <div class="major-theme">
            <a href="/indexArticles" class="theme-box rounded" style="color:black">
                <img src="/images/Article.png" style="width:100%">
            </a>
            <a href="/AudioFolder/PoadcastPage" class="theme-box rounded" style="color:black">
                <img src="/images/Podcast.png" style="width:100%">
            </a>
            <a href="/Tutoriel/Index" class="theme-box rounded" style="color:black">
                <img src="/images/Tuto.png" style="width:100%">
            </a>
        </div>

        <div class="articleContainer">

            <div class="articleBigContainer">
                @{

                    List<Article> lst = ViewData["lstArticles"] as List<Article>;
                    List<Article> lstArticle = new List<Article>();
                    foreach (Article article in lst)
                    {
                        if (article.EstPublier)
                        {
                            lstArticle.Add(article);
                        }
                    }


                    int nbArticle = lstArticle.Count();
                    if (nbArticle > 0)
                    {
                        Article unarticle = lstArticle[nbArticle - 1];

                            <div class="div-article1 shadow-lg rounded">

                                <a href="/Article?id=@unarticle.Id">
                                    <h4 class="articleTitle">@unarticle.Titre</h4>

                                    @if (unarticle.LienImg != null)
                                    {
                                        <img src="https://mediafileobjectifresiliance.s3.ca-central-1.amazonaws.com/@unarticle.LienImg" style="max-width:100%">
                                    }
                                    else
                                    {
                                        <img src="/images/imgplaceholder.png" style="width:100%">
                                    }
                                </a>
                            </div>
                        

                    }

                }
            </div>

            <div class="articleSmallContainer">
                @{
                    if (nbArticle > 1)
                    {
                        for (int i = 0; i < 2; i++)
                        {
                            nbArticle = lstArticle.Count();
                            Article unarticle = lstArticle[nbArticle - i - 2];

                            <div class="div-article shadow-lg rounded">
                                <a href="/Article?id=@unarticle.Id">
                                    <h4 class="articleTitle">@unarticle.Titre</h4>
                                    @if (unarticle.LienImg != null)
                                    {
                                        <img src="https://mediafileobjectifresiliance.s3.ca-central-1.amazonaws.com/@unarticle.LienImg" style="max-width:100%">
                                    }
                                    else
                                    {
                                        <img src="/images/imgplaceholder.png" style="width:100%">
                                    }

                                </a>
                            </div>
                        }
                    }


                }

            </div>
        </div>
    </div>
</div>

src/Web/Pages/NewPage.cshtml
@page
@using Web.Pages
@using Domain.Entities
@model Web.Pages.NewPagesModel
@{ ViewData["Title"] = "New page"; }





@{ NewPage aNewPage = ViewData["newPage"] as NewPage;
    string newPageContent = aNewPage.InerText;



    <h2 style="margin-bottom: 2rem; text-align: center">@aNewPage.Titre</h2>

    <div>
        @if (aNewPage.LienImg != null)
        {
            <img src="https://mediafileobjectifresiliance.s3.ca-central-1.amazonaws.com/@aNewPage.LienImg" class="divBanner" style="width: 100%; margin-bottom: 2rem;" />
        }
    </div>



    <div id="container" class="container">
        <div>
            <script>
            var article = '@newPageContent';
            tst = document.getElementById('container')


            function htmlDecode(input) {
                var e = document.createElement('div');
                e.innerHTML = input;
                return e.childNodes[0].nodeValue;
            }

            var tst2 = htmlDecode(article)
            tst.innerHTML += tst2;
            </script>
        </div>
    </div>
}

src/Web/Pages/indexArticles.cshtml
@page
@using Web.Pages
@using Microsoft.AspNetCore.Components.Forms
@using IdentityServer4.Extensions
@model Web.Pages.ArticleIndexModel
@{
    ViewData["Title"] = "Articles";
}

<!-- Entête de la page (Titre + barre de recherche) -->
<nav class="navbar navbar-light shadow-sm">
    <div class="container-fluid">
        <h1>Les articles</h1>
        @*@if (Model.Input.droitAccess == true)
                    {
            <form class="d-flex" method="post" asp-page="Index" style="display:flex; justify-content: center;">
                <button type="submit" class="btn btn-outline-primary" asp-page-handler="RedirectCreationTuto">Ajouter un tutoriel</button>
            </form>}*@
    </div>
</nav>



<div class="container-fluid">
    <br />
    <div class="main-content">

        <div class="row">
            <!-- Contenue du menu (Ou les filtres de recherche ce trouve) -->
            <div class="col-3" style="padding-right:1.5rem;padding-left:1.5rem;">
                <h4>Filtrer par :</h4>
                <hr />

                <!-- Btn Radio pour le mode de filtre. -->
                <div>
                    <form method="post" asp-page="indexArticles" enctype="multipart/form-data" id="formFiltre">
                        <!--<div class="input-group input-group-sm mb-3">
                    <label for="categorieDataList" style="width: 100%;">Sélectionner une catégorie</label>
                    <input class="form-control shadow-sm" list="categorieDatalistOptions" id="categorieDataList" placeholder="Écrire pour Sélectionner une catégorie..." name="cat">
                    <datalist id="categorieDatalistOptions">
                        <option id="filtreCategorieTous" value="Toutes" selected />-->
                        @*@if (!(@Model.Input.lstCategories.IsNullOrEmpty()))
                        {
                            @foreach (var cat in @Model.Input.lstCategories)
                            {
                                <option id="@cat.Id" value="@cat.Nom" />
                            }
                        }*@
                        <!--</datalist>
                    </div>-->

                        @if (Model.Input.droitAccess == false)
                        {
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" role="switch" id="radioFiltreEstPublie" name="radioFiltreEstPublie" value="true" checked hidden>
                                <label class="form-check-label" for="radioFiltreEstPublie" style="margin:0;" hidden>Est pubié</label>
                            </div>
                        }
                        else
                        {
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" role="switch" id="radioFiltreEstPublie" name="radioFiltreEstPublie" value="true" checked>
                                <label class="form-check-label" for="radioFiltreEstPublie" style="margin:0;">Est pubié</label>
                            </div>
                        }
                        <br />
                        <input class="form-control me-2" type="search" placeholder="Recherche" id="rechercheValeur" name="rechercheValeur">
                        <br />
                        <div style="display: flex;justify-content:center;">
                            <button data-filtreRecherche class="btn btn-outline-primary" type="submit" @*asp-page-handler="Recherche"*@>Rechercher</button>
                        </div>
                    </form>


            </div>
        </div>

        <!-- Contenue de la page (ou les articles ce trouve) -->
            <div class="col-9">
                <div class="pageDescriptionBox">
                    Voici un ensemble d'articles qui ont été produits lors des formations du Centre Jacques-Cartier.
                </div>
                <div class="row row-cols-1 row-cols-md-3 g-4" id="zoneCardTuto">

                </div>

                <br />
                <br />
            </div>
    </div>
        </div>
            <!-- Navigation de pagination -->
            <div>
                <ul class="pagination justify-content-center" id="navPagination">
                    <li class="page-item"><button class="page-link" style="background-color:#38b000;" data-paginationBtn id="btn-pagination-before">&laquo</button></li>

                    <li class="page-item"><button class="page-link" style="background-color:#38b000;" data-paginationBtn id="btn-pagination-after">&raquo</button></li>
                </ul>
            </div>
</div>

<script src="~/javascript/Article/recherche/script-recherche-utils.js" asp-append-version="true"></script>
<script src="~/javascript/Article/recherche/script-recherche-init.js" asp-append-version="true"></script>
@*<script src="~/javascript/Article/tutorielToastSupprimer.js" asp-append-version="true"></script>
    <script src="~/javascript/Article/tutorielToastUnPublish.js" asp-append-version="true"></script>*@

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js" integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>