src/Web/Pages/CreationTuto.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Globalization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using System.Reflection;
using System.Threading.Tasks;
using OfficeOpenXml;
using System.Linq;
using CsvHelper;
using CsvHelper.Configuration;
using Gwenael.Domain;
using Gwenael.Domain.Entities;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Packaging;
using NuGet.Protocol;
using OfficeOpenXml;
using Spk.Common.Helpers.String;


namespace Gwenael.Web.Pages
{
    public class CreationTutoModel : PageModel
    {
        [BindProperty]
        public InputModel Input { get; set; }

        private readonly GwenaelDbContext _context;

        public CreationTutoModel(GwenaelDbContext context)
        {
            _context = context;
        }

        public class InputModel
        {

        }
        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            return Page();
        }
    }
}

src/Web/Pages/Tutoriel/Consultation.cshtml.cs
using Gwenael.Domain;
using Gwenael.Domain.Entities;
using Gwenael.Web.FctUtils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spk.Common.Helpers.String;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;


namespace Gwenael.Web.Pages
{
    public class ConsultationModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public InputModel Input { get; set; }

        private readonly GwenaelDbContext _db;
        public IList<NewPage> NewPages { get; set; }

        public class InputModel
        {
            public Tutos tutoriel { get; set; }
            public List<RangeeTutos> lstRangeeTuto { get; set; }
            public string id { get; set; }
            public bool droitAccess { get; set; }
        }
        public ConsultationModel(GwenaelDbContext pDb)
        {
            _db = pDb;
        }

        public Guid ObtenirIdDuUserSelonEmail(string email)
        {
            User user = (User)_db.Users.Where(u => u.UserName == email).First();
            return user.Id;
        }
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            NewPages = _db.NewPages.ToList();
            ViewData["NewPages"] = NewPages;

            Input = new InputModel();

            Input.droitAccess = false;
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                {
                    Input.droitAccess = true;
                }
            }

            if (Request.Query.Count >= 1)
            {
                Input.id = Request.Query["id"];
                if (IdEstValide() && Input.droitAccess==true)
                {
                    return Page();
                } else if(IdEstValide() && Input.droitAccess==false && EstPublie())
                {
                    return Page();
                }
            }

            return Redirect("/tutoriel");
        }

        public IActionResult OnPost()
        {

            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            return Page();
        }

        public IActionResult OnPostRedirectHomeTuto()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            return RedirectToPage("Index");
        }

        public IActionResult OnPostUnpublishTuto([FromBody] TutorielIdVal tutoVal)
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                    if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                    {
                        Tutos t = _db.Tutos.Where(t => t.Id == Guid.Parse(tutoVal.tutorielIdVal)).First();
                        
                        bool status = false;
                        if (!t.EstPublier)
                            status = true;

                        _db.Tutos.Where(t => t.Id == Guid.Parse(tutoVal.tutorielIdVal)).First().EstPublier = status;
                        _db.SaveChanges();

                        return Redirect("/tutoriel?unPublishStatus=" + status);
                    }
                }
                return Redirect("/tutoriel");
            }
            catch (Exception)
            {
                return Redirect("/tutoriel");
            }
        }

        public class TutorielIdVal
        {
            public string tutorielIdVal { get; set; }
        }

        private bool IdEstValide()
        {
            if (!Input.id.IsNullOrEmpty())
            {
                if (_db.Tutos.Where(t => t.Id == Guid.Parse(Input.id)).Any())
                {
                    Input.tutoriel = _db.Tutos.Where(t => t.Id == Guid.Parse(Input.id)).First();
                    GetContenue();
                    return true;
                }
            }
            return false;
        }

        private bool EstPublie()
        {
            if (Input.tutoriel.EstPublier)
            {
                return true;
            }
            return false;
        }

        private void GetContenue()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            Input.lstRangeeTuto = _db.RangeeTutos.Where(r => r.TutorielId == Guid.Parse(Input.id)).ToList();
        }
    }
}

src/Web/Pages/Tutoriel/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Globalization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using System.Reflection;
using System.Threading.Tasks;
using OfficeOpenXml;
using System.Linq;
using CsvHelper;
using CsvHelper.Configuration;
using Gwenael.Domain;
using Gwenael.Domain.Entities;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Packaging;
using NuGet.Protocol;
using Spk.Common.Helpers.String;
using Gwenael.Web.FctUtils;

namespace Gwenael.Web.Pages
{
    public class TutorielIndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public InputModel Input { get; set; }
        private IList<NewPage> NewPages { get; set; }


        private readonly GwenaelDbContext _db;


        public class InputModel
        {
            public List<Tutos> lstTutoriels { get; set; }
            public bool droitAccess { get; set; }
            public List<CategoriesTutos> lstCategories { get; set; }

        }
        public TutorielIndexModel(GwenaelDbContext pDb) => _db = pDb;

        public Guid ObtenirIdDuUserSelonEmail(string email)
        {
            User user = (User)_db.Users.Where(u => u.UserName == email).First();
            return user.Id;
        }
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            NewPages = _db.NewPages.ToList();
            ViewData["NewPages"] = NewPages;

            Input = new InputModel();
            Input.droitAccess = false;
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                {
                    Input.droitAccess = true;
                }
            }
            Input.lstTutoriels = _db.Tutos.ToList();
            Input.lstCategories = _db.CategoriesTutos.ToList();

            return Page();
        }

        public IActionResult OnPost()
        {
            if (User.Identity.IsAuthenticated)
            {
                Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                if (Permission.EstAdministrateur(idConnectedUser, _db))
                {
                    ViewData["estAdmin"] = "true";
                }
            }
            else
            {
                ViewData["estAdmin"] = "false";
            }

            return Page();
        }

        public IActionResult OnPostRedirectCreationTuto() 
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                return RedirectToPage("CreationTuto");
            }

        public class RechercherFiltre
        {
            public bool radioFiltreEstPublie { get; set; }
            public string radioFiltre { get; set; }
            public string rechercheValeur { get; set; }
            public string cat { get; set; }
        }

        public IActionResult OnPostRecherche([FromForm] RechercherFiltre formData)
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                List<Tutos> t = new List<Tutos>();
                if (!formData.cat.IsNullOrEmpty() && formData.cat != "Toutes")
                {
                    List<CategoriesTutos> cats = _db.CategoriesTutos.Where(c => c.Nom.Contains(formData.cat)).ToList();
                    if (cats.Count > 0)
                    {
                        if (!formData.rechercheValeur.IsNullOrEmpty())
                        {
                            t = _db.Tutos.Where(t => t.EstPublier ==
                            formData.radioFiltreEstPublie && t.Categorie == cats[0]
                            && t.Titre.Contains(formData.rechercheValeur)).ToList();
                        }
                        else
                        {
                            t = _db.Tutos.Where(t => t.EstPublier ==
                            formData.radioFiltreEstPublie && t.Categorie == cats[0]).ToList();
                        }
                    }
                }
                else if (!formData.rechercheValeur.IsNullOrEmpty())
                {
                    List<CategoriesTutos> catTemp = _db.CategoriesTutos.ToList();
                    foreach (var item in catTemp)
                    {
                        t.AddRange(_db.Tutos.Where(t => t.EstPublier == formData.radioFiltreEstPublie
                        && t.Categorie == item && t.Titre.Contains(formData.rechercheValeur)).ToList());
                    }
                }
                else
                {
                    List<CategoriesTutos> catTemp = _db.CategoriesTutos.ToList();
                    foreach (var item in catTemp)
                    {
                        t.AddRange(_db.Tutos.Where(t => t.EstPublier == formData.radioFiltreEstPublie && t.Categorie == item).ToList());
                    }
                }
                return StatusCode(201, new JsonResult(t));
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }

        public IActionResult OnPostObtenirDroit()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = FctUtils.Permission.ObtenirIdDuUserSelonEmail(User.Identity.Name, _db);
                    if (Permission.EstAdministrateur(idConnectedUser, _db))
                    {
                        ViewData["estAdmin"] = "true";
                    }
                }
                else
                {
                    ViewData["estAdmin"] = "false";
                }

                if (User.Identity.IsAuthenticated)
                {
                    Guid idConnectedUser = ObtenirIdDuUserSelonEmail(User.Identity.Name);
                    if (Permission.VerifierAccesGdC(idConnectedUser, _db))
                    {
                        return StatusCode(200, true);
                    }
                }
                return StatusCode(200, false);
            }
            catch (Exception)
            {
                return StatusCode(400);
            }
        }
    }
}

src/Web/Pages/Tutoriel/Consultation.cshtml
@page
@using Web.Pages
@using Microsoft.AspNetCore.Components.Forms
@using IdentityServer4.Extensions
@model Web.Pages.ConsultationModel
@{
    ViewData["Title"] = "Consultation tutoriel";
    var tuto = @Model.Input.tutoriel;
    var rangee = Model.Input.lstRangeeTuto;
}

@if (@Model.Input.tutoriel != null)
{
    <!-- Entête de la page (Titre + btn retour) -->
    <nav class="navbar navbar-light shadow-sm">
        <div class="container-fluid">
            <h1>Tutoriel</h1>
            <div class="d-flex">
                <form method="post" asp-page="CreationTuto" style="margin-right:0.4rem;">
                    <button type="submit" class="btn btn-outline-primary" asp-page-handler="RedirectHomeTuto">Retour</button>
                </form>

                @if (Model.Input.droitAccess)
                {
                    @if (!Model.Input.tutoriel.EstPublier)
                    {
                        <a class="btn btn-outline-primary" href="/Tutoriel/CreationTuto?handler=TutoRangee&id=@tuto.Id" style="margin-right: 5px;">Modifié</a>
                    }
                    else
                    {
                        <button class="btn btn-outline-primary disabled" style="margin-right: 5px;" title="test">Modifié</button>
                    }
                    <form method="post" asp-page="Consultation">
                        <input name="tutorielIdVal" type="text" value="@tuto.Id" hidden />
                        @if(Model.Input.tutoriel.EstPublier){
                            <button type="submit" class="btn btn-primary" data-UnpublishTuto asp-page-handler="UnpublishTuto" data-bs-toggle="modal" data-bs-target="#modalValideUnpublishTuto" name="nonPublic">Rendre non public</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary" data-UnpublishTuto asp-page-handler="UnpublishTuto" data-bs-toggle="modal" data-bs-target="#modalValideUnpublishTuto" name="public">Rendre public</button>
                        }
                    </form>   
                }
            </div>
        </div>
    </nav>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        @if (!@tuto.LienImgBanniere.IsNullOrEmpty())
                        {
                            <a href="@tuto.LienImgBanniere" target="_blank">
                                <img src="@tuto.LienImgBanniere" class="card-img-top shadow-lg" alt="..." style="max-width:33.75rem;max-height:19.063rem;">
                            </a>
                        }
                        else
                        {
                            <img src="~/images/imgplaceholder.png" class="card-img-top shadow-lg" alt="..." style="max-width:33.75rem;max-height:19.063rem;">
                        }
                    </div>
                    <div class="col-md-6">
                        <h2>@tuto.Titre</h2>
                        @if (Model.Input.droitAccess == true)
                        {
                            @if (@tuto.EstPublier == true)
                            {
                                <p style="font-weight: bold;">Publié le @tuto.DateCreation.ToString("dd/MM/yyyy")</p>
                                <p style="color:#38b000; font-weight: bold;">État: Publié</p>
                            }
                            else
                            {
                                <p style="font-weight: bold;">Publié le @tuto.DateCreation.ToString("dd/MM/yyyy")</p>
                                <p style="color:#ff7733;font-weight: bold;">État: Non Publié</p>
                            }
                        }
                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text" id="inputDuree">Durée (heures)</span>
                            <input type="number" class="form-control" aria-label="Durée" aria-describedby="Durée" value="@tuto.Duree" disabled>
                        </div>

                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text" id="inputCout">Cout</span>
                            <input type="number" class="form-control" aria-label="Cout" aria-describedby="Cout" value="@tuto.Cout" disabled>
                            <span class="input-group-text">$</span>
                        </div>

                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text" id="inputCout">Difficulte</span>
                            <input type="number" class="form-control" aria-label="Difficulte" aria-describedby="Difficulte" value="@tuto.Difficulte" disabled>
                        </div>
                        <div>
                        </div>
                        <textarea class="input-group input-group-sm mb-3" style="resize: none;" disabled rows="4">@tuto.Materiels</textarea>
                    </div>
                </div>
                <br />
                <br />
                <div class="shadow-sm rounded" style="background-color:#f1f9ee; padding:0.7rem; margin-bottom:1.2rem; margin-top:0.7rem;">
                    <h2 class="col-6" style="display:inline; text-align:left;">Introduction</h2>
                    <div class="card-body row">
                        <p style="text-align:justify;">@tuto.Introduction</p>
                    </div>
                </div>
                <br>
                @if (!@Model.Input.lstRangeeTuto.IsNullOrEmpty())
                {
                    @foreach (var row in rangee)
                    {
                        <div class="shadow-sm rounded" style="background-color:#f1f9ee; padding:0.7rem; margin-bottom:1.2rem; margin-top:0.7rem;">

                            <h3 class="col-6" style="display:inline; text-align:left;">@row.Titre</h3>

                            <div class="card-body row">
                                <!-- Contenue de la rangéé. -->
                                @if (!row.LienImg.IsNullOrEmpty())
                                {
                                    @if (!row.Texte.IsNullOrEmpty())
                                    {
                                        @if (row.PositionImg == "left")
                                        {
                                            <div class="col-md-4">
                                                <a href="@row.LienImg" target="_blank">
                                                    <img src="@row.LienImg" class="card-img-top" style="max-height:20rem; max-width:30rem;" alt="...">
                                                </a>
                                            </div>
                                            <div class="col-md-8">
                                                <p class="card-text" style="text-align:justify;">@row.Texte</p>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="col-md-8">
                                                <p class="card-text" style="text-align:justify;">@row.Texte</p>
                                            </div>
                                            <div class="col-md-4">
                                                <a href="@row.LienImg" target="_blank">
                                                    <img src="@row.LienImg" class="card-img-top" style="max-height:20rem; max-width:30rem;" alt="...">
                                                </a>
                                            </div>
                                        }
                                    }
                                    else
                                    {
                                        <a href="@row.LienImg" target="_blank" style="text-align: center;">
                                            <img src="@row.LienImg" class="card-img-top" style="max-height:20rem; max-width:30rem;" alt="...">
                                        </a>
                                    }
                                }
                                else
                                {
                                    <p class="card-text" style="text-align:justify;">@row.Texte</p>
                                }
                            </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>
}

<div class="modal" id="modalValideUnpublishTuto" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalValideUnpublishTutoLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalValideUnpublishTutoLabel">Confirmation!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Voulez-vous vraiment mettre à jour le Status du tutoriel?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Non</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="btnConfirmUnpublishTuto">Oui</button>
            </div>
        </div>
    </div>
</div>

<div id="toastTutoPublishDiv" class="position-fixed bottom-0 end-0 p-3" style="z-index: 11" hidden>
    <div id="toastTutoPublish" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-animation="true" data-bs-delay="5000">
        <div class="toast-header">
            <img style="max-width:1.5rem;max-height:1.5rem;" src="/icons/valide.svg" class="rounded me-2" alt="...">
            <strong class="me-auto">Confirmation publication</strong>
            <small>Nouveau!</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">Le tutoriel a bien été publié!</div>
    </div>
</div>

<script src="~/javascript/Tutoriel/tutorielUnpublish.js" asp-append-version="true"></script>
<script src="~/javascript/Tutoriel/tutorielToastPublish.js" asp-append-version="true"></script>